### ISSUE TITLE
This plugins occur 500 Internal Server Error

### ISSUE THREAD

**Issue by dreampet** [efigence/redmine_overwriting_roles#1]
My Redmine Version info:
Environment:
  Redmine version                3.1.2.stable
  Ruby version                   2.1.7-p400 (2015-08-18) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2
SCM:
  Cvs                            1.12.13
  Git                            1.9.1
  Filesystem  
Redmine plugins:
  a_common_libs                  1.1.6
  advanced_roadmap_v2            2.4.2
  clipboard_image_paste          1.10
  file_servers                   3.0.2
  redmine_banner                 0.1.1
  redmine_checklists             3.1.3
  redmine_code_review            0.7.0
  redmine_revision_branches      0.3.0
  redmine_work_time              0.3.1
  usability                      2.0.0

if install this plugin and login user with LDAP auth, it occur a 500 server error.

the error log:

Started POST "/login" for 192.168.1.102 at 2015-12-03 09:56:19 +0800
Processing by AccountController#login as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"U21XpidGJead++P1GjxC8t4uuE20RDELMm1uPjm5t+QN/bVUSF6owo8EXWIRP9RO/k5fim08JR1bPHPnuv9ySA==", "back_url"=>"http://192.168.1.200/", "username"=>"test2", "password"=>"[FILTERED]", "login"=>"login »"}
  Current user: anonymous
Completed 500 Internal Server Error in 47ms (ActiveRecord: 2.2ms)

NoMethodError (private method `timeout' called for #<AuthSourceLdap:0x007fd45f2c2320>):
  app/models/auth_source_ldap.rb:95:in`with_timeout'
  app/models/auth_source_ldap.rb:41:in `authenticate'
  app/models/user.rb:307:in`check_password?'
  app/models/user.rb:213:in `try_to_login'
  app/controllers/account_controller.rb:194:in`password_authentication'
  app/controllers/account_controller.rb:189:in `authenticate_user'
  app/controllers/account_controller.rb:40:in`login'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by linnal** [comment]
Did you understand why this was happening?

**Comment by StuartWhelan** [comment]
I am getting this also. Is this plugin still maintained?
